=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/transactionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/transactionSchema"
	xmlns:tns="http://www.example.org/transactionSchema">
	<annotation>
		<documentation xml:lang="en">
			Department schema Copyright 2000 Example.com. All rights
			reserved.
		</documentation>
	</annotation>
	<element name="Transaction" type="tns:transactionType"></element>
	<complexType name="transactionType">
		<sequence>
			<element name="OPR" type="tns:oprType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		
		<attribute name="MODULE_NAME" type="string"></attribute>
		<attribute name="PROCESS_NAME" type="string"></attribute>
	</complexType>
	<complexType name="oprType">
		<sequence>
			<element name="BLOCK" type="tns:blockType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="ID" type="string"></attribute>
		<attribute name="NAME" type="string"></attribute>
		<attribute name="BLOCK_SIZE" type="string"></attribute>
		<attribute name="QRY_TOT_SIZE" type="string"></attribute>
		<attribute name="TRN_MGMT" type="string"></attribute>
	</complexType>
	<complexType name="blockType">
		<sequence>
			<element name="QRY" maxOccurs="unbounded">	
			<complexType>
				<simpleContent>
					<extension base="string">
						<attribute name="ID" type="string"></attribute>
						<attribute name="COL_SIZE" type="string"></attribute>
					</extension>	
				</simpleContent>
			</complexType>		
			</element>
		</sequence>
		<attribute name="ID" type="string"></attribute>
		<attribute name="QRY_SIZE" type="string"></attribute>
		<attribute name="MANDATORY" type="string"></attribute>
		<attribute name="ROWS_INS" type="string"></attribute>
	</complexType>
	
</schema>

=== anuragdes/HFMS-E-BIS-/OPT/oldxml/CashChallanFormAODAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="CASH" PROCESS_NAME="Challan Form Acceptance" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">

<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="13">
 INSERT INTO ACTCAS_CHAL_APRV_TRN(STR_CHALLAN_NO,DT_CHALLAN_DATE,STR_APPROVE_BY_AO,STR_APPROVE_BY,DT_APPROVAL_DATE,STR_REMARKS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE,GDT_ENTRY_DATE ,GNUM_ISVALID ,GNUM_SEAT_ID ,gnum_hospital_code) values (?,?,?,?,?,?,?,?,?,?,?,?,?)	 
</QRY>
</BLOCK>
</OPR>

<OPR ID="2" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="2">
 INSERT INTO ACTCAS_AL_CHAL_APRV_TRN(STR_CHALLAN_NO,DT_CHALLAN_DATE,STR_APPROVE_BY_AO,STR_APPROVE_BY,DT_APPROVAL_DATE,STR_REMARKS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE,GDT_ENTRY_DATE ,GNUM_ISVALID ,GNUM_SEAT_ID ,gnum_hospital_code,STR_MODIFY_SL_NO ) (SELECT T.STR_CHALLAN_NO,T.DT_CHALLAN_DATE,T.STR_APPROVE_BY_AO,T.STR_APPROVE_BY,T.DT_APPROVAL_DATE,T.STR_REMARKS ,T.GDT_LSTMOD_DATE,T.GNUM_LSTMOD_SEATID,T.GDT_EFFECT_DATE,T.GDT_ENTRY_DATE ,T.GNUM_ISVALID ,T.GNUM_SEAT_ID ,T.gnum_hospital_code,(select nvl(max(A.STR_MODIFY_SL_NO),0)+1 from ACTCAS_AL_CHAL_APRV_TRN A where A.STR_CHALLAN_NO=T.STR_CHALLAN_NO and A.GNUM_HOSPITAL_CODE=T.GNUM_HOSPITAL_CODE) FROM ACTCAS_CHAL_APRV_TRN T WHERE T.STR_CHALLAN_NO=? AND T.gnum_hospital_code=? )	 
</QRY>
</BLOCK>
<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="8">
 UPDATE  ACTCAS_CHAL_APRV_TRN Y SET Y.STR_APPROVE_BY_AO=?,Y.STR_APPROVE_BY=?,Y.DT_APPROVAL_DATE=?,Y.STR_REMARKS=? ,Y.GDT_LSTMOD_DATE=?,Y.GNUM_LSTMOD_SEATID=? WHERE Y.STR_CHALLAN_NO=? AND Y.GNUM_HOSPITAL_CODE=?
</QRY>
</BLOCK>
</OPR>

<OPR ID="4" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="3">
 UPDATE  ACTCAS_CHAL_TRN T SET T.STR_CHALLAN_STATUS	=? WHERE T.STR_CHALLAN_NO=?	AND T.gnum_hospital_code=?	
</QRY>
</BLOCK>
</OPR>

<OPR ID="5" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="3">
 UPDATE  ACTCAS_CHAL_ONLINE_TRN T SET T.STR_CHALLAN_STATUS=? WHERE T.STR_CHALLAN_NO=? AND T.GNUM_HOSPITAL_CODE=?	
</QRY>
</BLOCK>
</OPR>

</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/ftsRniSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="FTS" PROCESS_NAME="RniMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="13">
	 INSERT INTO FTS_RNI_MST (NUM_RNI_ID,GNUM_SLNO,STR_RNI_CODE,STR_RNI_NAME,NUM_DEPT_CODE,NUM_USER_ID, GSTR_REMARKS, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GDT_ENTRY_DATE, GNUM_SEAT_ID, GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

  <OPR ID="2" NAME="UPDATE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="4">
	 UPDATE FTS_RNI_MST SET GNUM_ISVALID=0, GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=? WHERE NUM_RNI_ID=? AND GNUM_SLNO=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="13">
	  INSERT INTO FTS_RNI_MST (NUM_RNI_ID,GNUM_SLNO,STR_RNI_CODE,STR_RNI_NAME,NUM_DEPT_CODE,NUM_USER_ID, GSTR_REMARKS, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GDT_ENTRY_DATE, GNUM_SEAT_ID, GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="4">
	 UPDATE FTS_RNI_MST SET GNUM_ISVALID=0, GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=? WHERE NUM_RNI_ID=? AND GNUM_SLNO=?
	</QRY>
	</BLOCK>
</OPR>

</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/Est_quarterAllotSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="ESTATE" PROCESS_NAME="Quarter Allotment Details" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">

<OPR ID="1" NAME="INSERT" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="31">
	 INSERT INTO EST_QUATER_ALLOTMENT_DTL (NUM_HOSPITAL_ID,NUM_BUILDING_CODE,GNUM_SLNO_B,NUM_BLOCK_TYPE_ID,NUM_BLOCK_ID,GNUM_SLNO_BLK,NUM_FLOOR_ID,GNUM_SLNO_F,NUM_QUARTER_ID,GNUM_SLNO_QTR,NUM_QUARTER_TYPE_ID,GNUM_SLNO_QTY,STR_ALLOTTE_CATEGORY,STR_EMPLOYEE_CODE,NUM_ALLOTTE_REF_NO,DT_DATE_OF_ALLOTMENT,NUM_LICENSE_FEE,NUM_IF_EXEMPTED,STR_SANCTION_ORDER_NO,DT_SANCTION_ORDER_DATE,STR_SANCTION_REMARKS,NUM_ELECTRICITY_AMOUNT,NUM_WATER_AMOUNT,DT_POSSESSION_DATE,DT_MAX_POSSESSION_DATE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GBL_NUM_SEAT_ID,STR_STATUS,NUM_APPLICATION_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
    <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QUATER_MST A SET A.STR_STATUS_FLAG='B' WHERE A.NUM_QUARTER_ID=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_REQ_APPLICATION_FORM_DTL A SET A.GNUM_ISVALID=2 WHERE A.NUM_APPLICATION_ID=? 
	</QRY>
	</BLOCK>
</OPR>


<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="22">
	  UPDATE EST_QUATER_ALLOTMENT_DTL SET DT_DATE_OF_ALLOTMENT=?,NUM_LICENSE_FEE=?,NUM_IF_EXEMPTED=?,
	  STR_SANCTION_ORDER_NO=?,DT_SANCTION_ORDER_DATE=?,STR_SANCTION_REMARKS=?,NUM_ELECTRICITY_AMOUNT=?,NUM_WATER_AMOUNT=?,DT_POSSESSION_DATE=?,DT_MAX_POSSESSION_DATE=?,
	  STR_POS_AFTER_RET=?,NUM_REV_LICENSE_FEE=?, DT_APP_LIC_FEE=?, STR_RES_REV_LINCE_FEE=?, DT_POS_START_RET_DATE=?,DT_POS_END_RET_DATE=?,STR_ACCEPT_FLAGE=?, DT_ACCEPT_DATE=?,
	  GDT_EFFECT_DATE=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_ALLOTTE_REF_NO=? 
	 </QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QUATER_MST A SET A.STR_STATUS_FLAG='A' WHERE A.NUM_QUARTER_ID=? 
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 DELETE FROM EST_QTR_ALLOT_ELEC_METER_DTL A WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 DELETE FROM EST_QTR_ALLOT_WATER_METER_DTL A WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="4" NAME="DELETE WHOLE" BLOCK_SIZE="4" QRY_TOT_SIZE="4" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QUATER_ALLOTMENT_DTL A SET A.GNUM_ISVALID=0,A.STR_STATUS='V' WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>

	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QTR_ALLOT_ELEC_METER_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QTR_ALLOT_WATER_METER_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="4" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QUATER_MST A SET A.STR_STATUS_FLAG='N' WHERE A.NUM_QUARTER_ID=? 
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="5" NAME="INSERT INVENTORY" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="12">
	 INSERT INTO EST_QTR_ITEMCROSSCHECK_DTL (NUM_ALLOTTE_REF_NO,DT_CROSSCHECKED_DATE,STR_ITEM_CATEGORY_NAME,STR_ITEM_NAME,NUM_ITEM_ID,STR_CHECK_LIST_STATUS,STR_CHECK_LIST_DESC,STR_ACCEPTANCE,DT_EFFECT_DATE,DT_ENTRY_DATE,NUM_IS_VALID,GBL_NUM_SEAT_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) 
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="6" NAME="INSERT ELECTRICITY" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_QTR_ALLOT_ELEC_METER_DTL (NUM_ALLOTTE_REF_NO,STR_METER_BY,STR_METER_NUMBER,DT_DATE_OF_INSTALLATION,DT_DATE_OF_REMOVAL,STR_DESCRIPTION,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GBL_NUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
   </OPR>
<OPR ID="7" NAME="INSERT WATER" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_QTR_ALLOT_WATER_METER_DTL (NUM_ALLOTTE_REF_NO,STR_METER_BY,STR_METER_NUMBER,DT_DATE_OF_INSTALLATION,DT_DATE_OF_REMOVAL,STR_DESCRIPTION,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GBL_NUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="8" NAME="DELETE CHECKLIST" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="1">
	  DELETE FROM EST_QTR_ITEMCROSSCHECK_DTL A WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="9" NAME="UPDATE_OFFER_ALLOT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="5">
	  UPDATE  EST_QUATER_ALLOTMENT_DTL  SET STR_OFFER_LETTER_NO =? , DT_OFFER_LETTER=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="10" NAME="UPDATE_ACCEPT_ALLOT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="7">
	  UPDATE  EST_QUATER_ALLOTMENT_DTL  SET STR_ACCEPT_FLAGE=? , DT_ACCEPT_DATE=?,DT_POSSESSION_DATE=?,DT_EXPECT_VACATION=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
</OPR>

<OPR ID="11" NAME="UPDATE_ACCEPT_ALLOT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="7">
	  UPDATE  EST_QUATER_ALLOTMENT_DTL  SET STR_ACCEPT_FLAGE=? , DT_ACCEPT_DATE=?,DT_POSSESSION_DATE=?,DT_EXPECT_VACATION=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
    <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="3">
	  UPDATE EST_REQ_APPLICATION_FORM_DTL A SET A.STR_FINAL_ACEP_REJ_NEX='N',A.GNUM_ISVALID=1 ,A.STR_AUTO_PRIORITY='', A.STR_MANUAL_PRIORITY='',GDT_LSTMOD_DATE=? , GNUM_LSTMOD_SEATID=?   WHERE A.NUM_APPLICATION_ID=? 
	</QRY>
   </BLOCK>
</OPR>

<OPR ID="12" NAME="UPDATE_ALLOT_LETTER" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="5">
	  UPDATE  EST_QUATER_ALLOTMENT_DTL SET STR_ALLOT_LETTER_NO=?, DT_ALLOT_LETTER=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=?  WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
</OPR>

</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/buildingSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="ESTATE" PROCESS_NAME="buildingMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="11">
	 INSERT INTO EST_BUILDING_MST (NUM_HOSPITAL_CODE,NUM_BUILDING_CODE,GNUM_SLNO,STR_BUILDING_NAME,NUM_TOT_BLOCK_NUMBER,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>



<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="9">
	 UPDATE EST_BUILDING_MST SET STR_BUILDING_NAME=?, NUM_TOT_BLOCK_NUMBER=?,  GSTR_REMARKS=?, GDT_EFFECTIVE_FRM=?,GDT_EFFECTIVE_TO=?,GNUM_ISVALID=?  WHERE GNUM_SLNO=? AND NUM_BUILDING_CODE=? AND NUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	
</OPR>

<OPR ID="3" NAME="INSERT" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="N">
	
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="4">
	 UPDATE EST_BUILDING_MST T SET T.GDT_EFFECTIVE_TO=(to_date(?,'DD-MON-YYYY')-1) WHERE T.NUM_BUILDING_CODE=? and T.GNUM_SLNO=? and T.NUM_HOSPITAL_CODE=?
	 </QRY>
	 
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="14">
	 INSERT INTO EST_BUILDING_MST (NUM_HOSPITAL_CODE,NUM_BUILDING_CODE,GNUM_SLNO,STR_BUILDING_NAME,NUM_TOT_BLOCK_NUMBER,STR_BUILDING_MAP_ID,STR_BUILDING_MAP_LOC,STR_BUILDING_MAP_DESCR,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	 UPDATE EST_BUILDING_MST T SET T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=?  WHERE T.GNUM_SLNO=? AND T.NUM_BUILDING_CODE=? AND T.NUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	
</OPR>

<OPR ID="4" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	 UPDATE EST_BUILDING_MST T SET T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=?, T.GNUM_ISVALID=0 WHERE T.GNUM_SLNO=? AND T.NUM_BUILDING_CODE=? AND T.NUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="5" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	 UPDATE EST_BUILDING_MST T SET T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=?  WHERE T.GNUM_SLNO=? AND T.NUM_BUILDING_CODE=? AND T.NUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="14">
	 INSERT INTO EST_BUILDING_MST (NUM_HOSPITAL_CODE,NUM_BUILDING_CODE,GNUM_SLNO,STR_BUILDING_NAME,NUM_TOT_BLOCK_NUMBER,STR_BUILDING_MAP_ID,STR_BUILDING_MAP_LOC,STR_BUILDING_MAP_DESCR,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	
	
</OPR>

<OPR ID="6" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
 <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
  <QRY ID="1" COL_SIZE="1">DELETE FROM EST_MAP_MST  WHERE NUM_ID=? and GNUM_ISVALID=1 </QRY> 
  </BLOCK>
  <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="8">
	 INSERT INTO EST_MAP_MST (NUM_HOSPITAL_CODE,NUM_ID,GNUM_SLNO,STR_LAND_MAP_LOCATION,STR_LAND_DESC,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE) VALUES (?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
 
  </OPR>
  
  
<OPR ID="7" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
 <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="8">
	 INSERT INTO EST_MAP_MST (NUM_HOSPITAL_CODE,NUM_ID,GNUM_SLNO,STR_LAND_MAP_LOCATION,STR_LAND_DESC,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE) VALUES (?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	 
  </OPR>

</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/xml/hkAreaCleaningSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:Transaction MODULE_NAME="HOUSEKEEPING" PROCESS_NAME="AreaCleaningMapMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="11">
	 INSERT INTO HK_AREA_CLEANING_MAPPING(NUM_HK_AREA_ID, STR_DAY_ID, GNUM_HOSPITAL_CODE, GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE, HDRNUM_SHIFT_ID, STR_CLEANING_FREQUENCY_ID, NUM_CLEANING_PARAMETER_ID, NUM_SAFETY_PARAMETER_ID, GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	
</OPR>

<OPR ID="2" NAME="Update" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="2">
	 DELETE FROM HK_AREA_CLEANING_MAPPING A WHERE A.NUM_HK_AREA_ID=? AND  A.GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="11">
	 INSERT INTO HK_AREA_CLEANING_MAPPING(NUM_HK_AREA_ID,  STR_DAY_ID, GNUM_HOSPITAL_CODE, GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE, HDRNUM_SHIFT_ID, STR_CLEANING_FREQUENCY_ID, NUM_CLEANING_PARAMETER_ID, NUM_SAFETY_PARAMETER_ID, GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	 </QRY>
	 </BLOCK>
</OPR>

<OPR ID="3" NAME="Delete" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="2">
	DELETE FROM HK_AREA_CLEANING_MAPPING A WHERE NUM_HK_AREA_ID=? and GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>
</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/IdCard_lostidcardSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="COMITTEE" PROCESS_NAME="ID Card Transaction" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">

  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="12">
	 INSERT INTO PISCOM_LOST_ICARD_TRN(GNUM_HOSPITAL_CODE,STR_ID_CARD_NUMBER,DT_LOST_DATE,DT_COMPLAIN_DATE,STR_FIR_NO,DT_FIR_DATE,STR_POLICE_STATION,STR_PLACE_WHERE_LOST,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="4">
	 UPDATE piscom_id_entry_trn SET STR_LOST_FLAG_STATUS=? where STR_ID_CARD_NUMBER=? and STR_LOST_FLAG_STATUS=? and GNUM_HOSPITAL_CODE=?
	</QRY>
   </BLOCK>

</OPR>

<OPR ID="2" NAME="MODIFY" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="Y">

   <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="10">
     UPDATE PISCOM_LOST_ICARD_TRN SET DT_LOST_DATE=?,DT_COMPLAIN_DATE=?,STR_FIR_NO=?,DT_FIR_DATE=?,STR_POLICE_STATION=?,STR_PLACE_WHERE_LOST=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE STR_ID_CARD_NUMBER=? AND GNUM_HOSPITAL_CODE=?
    </QRY>
  </BLOCK>
</OPR>

<OPR ID="3" NAME="delete" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="2">
     UPDATE PISCOM_LOST_ICARD_TRN a SET a.gnum_isvalid=0 WHERE a.str_id_card_number=? AND A.GNUM_HOSPITAL_CODE=?   
    </QRY>
   </BLOCK>
   <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="4">
	 UPDATE piscom_id_entry_trn SET STR_LOST_FLAG_STATUS=? where STR_ID_CARD_NUMBER=? and GNUM_HOSPITAL_CODE=? and STR_LOST_FLAG_STATUS=? 	
	</QRY>
   </BLOCK>
</OPR>



</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/oldxml/DeptLedgerHeadSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="BUDGET" PROCESS_NAME="grantTypeMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="16">
	 	INSERT INTO ACTCON_DPT_LED_HED_MST(STR_GRANT_TYPE_CODE,NUM_DPT_LED_HED_ID,NUM_DPT_CODE,STR_ADD,STR_OFF_FAX_NO,STR_OFF_PH_NO,STR_MOB_NO,STR_DEPT_LEDGER_CODE,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GSTR_REMARKS,GDT_ENTRY_DATE,GNUM_SLNO,GNUM_ISVALID,GNUM_SEAT_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>


<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="13">
	    UPDATE ACTCON_DPT_LED_HED_MST SET STR_GRANT_TYPE_CODE=?,NUM_DPT_CODE=?,STR_ADD=?,STR_OFF_FAX_NO=?,STR_OFF_PH_NO=?,STR_MOB_NO=?,GDT_EFFECTIVE_FRM=TO_DATE(?,'DD-MON-YYYY'),GDT_EFFECTIVE_TO=TO_DATE(?,'DD-MON-YYYY'),GSTR_REMARKS=? ,GNUM_ISVALID=? WHERE NUM_DPT_LED_HED_ID=? AND GNUM_SLNO=? AND GNUM_HOSPITAL_CODE=?       
		</QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="MODIFICATION" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	  UPDATE ACTCON_DPT_LED_HED_MST T SET T.GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1),T.GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')),T.GNUM_LSTMOD_SEATID=? WHERE T.NUM_DPT_LED_HED_ID=? AND T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="18">
	 INSERT INTO ACTCON_DPT_LED_HED_MST(NUM_DPT_LED_HED_ID,NUM_DPT_CODE,STR_ADD,STR_OFF_FAX_NO,STR_OFF_PH_NO,STR_MOB_NO,STR_DEPT_LEDGER_CODE,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GSTR_REMARKS,GDT_ENTRY_DATE,GNUM_SLNO,GNUM_ISVALID,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GNUM_SEAT_ID,GNUM_HOSPITAL_CODE,STR_GRANT_TYPE_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="4" NAME="MODIFICATION" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	  UPDATE ACTCON_DPT_LED_HED_MST T SET T.GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')),T.GNUM_LSTMOD_SEATID=?  WHERE T.NUM_DPT_LED_HED_ID=? AND T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
	
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="18">	    				
	 INSERT INTO ACTCON_DPT_LED_HED_MST (NUM_DPT_LED_HED_ID,NUM_DPT_CODE,STR_ADD,STR_OFF_FAX_NO,STR_OFF_PH_NO,STR_MOB_NO,STR_DEPT_LEDGER_CODE,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GSTR_REMARKS,GDT_ENTRY_DATE,GNUM_SLNO,GNUM_ISVALID,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GNUM_SEAT_ID,GNUM_HOSPITAL_CODE,STR_GRANT_TYPE_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)	
	</QRY>
	</BLOCK>
</OPR>
	
<OPR ID="5" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	  UPDATE ACTCON_DPT_LED_HED_MST T  SET T.GNUM_ISVALID=0,T.GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')),T.GNUM_LSTMOD_SEATID=? WHERE  T.NUM_DPT_LED_HED_ID= ? AND T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
     </QRY>
   </BLOCK>
</OPR>

		
																							
</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/PaymentOrderGenSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:Transaction MODULE_NAME="HR" PROCESS_NAME="PaymentOrderGen" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">

<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="17">
INSERT INTO PISLEG_CASE_PO_GEN_TRN (GNUM_HOSPITAL_CODE,STR_CASE_ID, STR_CASE_NUMBER, NUM_DEPT_CODE, NUM_ADV_ID, NUM_COURT_ID, NUM_TOTAL_AMOUNT, STR_PO_ORDER_NUMBER, DT_PO_ORDER_DATE, STR_PO_ORDER_PLACE_BY,  NUM_UPDATION_FLAG,GDT_LSTMOD_DATE, GNUM_LSTMOD_SEATID, GDT_EFFECT_DATE, GDT_ENTRY_DATE, GNUM_ISVALID, GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
</QRY>
</BLOCK>
</OPR>


<OPR ID="2" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="20">
INSERT INTO PISLEG_CASE_PO_GEN_DTL (GNUM_HOSPITAL_CODE,STR_CASE_ID,STR_CASE_NUMBER,STR_PO_ORDER_NUMBER,DT_PO_ORDER_DATE,DT_FROM_PAYMENT_PERIOD,DT_TO_PAYMENT_PERIOD,STR_TYPE_OF_PAYMENT,NUM_ADV_FEE_CASE_BAS,NUM_ADV_FEE_HEAR_BASIS,NUM_CONF_FEE,DT_OF_CONFERENCE,STR_MISC_EXP,STR_MISC_EXP_AMOUNT,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
</QRY>
</BLOCK>
</OPR>


<OPR ID="3" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">

<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="13">

</QRY>
</BLOCK>

<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="13">

</QRY>
</BLOCK>

</OPR>


<OPR ID="4" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="2">
DELETE FROM PISLEG_CASE_PO_GEN_DTL A WHERE STR_PO_ORDER_NUMBER=? and GNUM_HOSPITAL_CODE=? 
</QRY>
</BLOCK>
</OPR>


<OPR ID="5" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="18">

UPDATE PISLEG_CASE_PO_GEN_TRN A SET A.STR_CASE_ID=?, A.STR_CASE_NUMBER=?, A.NUM_DEPT_CODE=?, A.NUM_ADV_ID=?, A.NUM_COURT_ID=?, A.NUM_TOTAL_AMOUNT=?, A.STR_PO_ORDER_NUMBER=?,  A.DT_PO_ORDER_DATE=?, A.STR_PO_ORDER_PLACE_BY=?, A.NUM_UPDATION_FLAG=?, A.GDT_LSTMOD_DATE=?, A.GNUM_LSTMOD_SEATID=?, A.GDT_EFFECT_DATE=?, A.GDT_ENTRY_DATE=?, A.GNUM_ISVALID=?, A.GNUM_SEAT_ID=? WHERE A.STR_PO_ORDER_NUMBER=? and A.GNUM_HOSPITAL_CODE=? 
</QRY>
</BLOCK>
</OPR>


<OPR ID="6" NAME="UPDATE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">

<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="2">
UPDATE PISLEG_CASE_PO_GEN_TRN SET GNUM_ISVALID=0 WHERE STR_PO_ORDER_NUMBER=? and GNUM_HOSPITAL_CODE=?  
</QRY>
</BLOCK>

<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
<QRY ID="1" COL_SIZE="2">
UPDATE PISLEG_CASE_PO_GEN_DTL SET GNUM_ISVALID=0 WHERE STR_PO_ORDER_NUMBER=? and GNUM_HOSPITAL_CODE=?  
</QRY>
</BLOCK>

</OPR>


</tns:Transaction>
