=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/transactionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/transactionSchema"
	xmlns:tns="http://www.example.org/transactionSchema">
	<annotation>
		<documentation xml:lang="en">
			Department schema Copyright 2000 Example.com. All rights
			reserved.
		</documentation>
	</annotation>
	<element name="Transaction" type="tns:transactionType"></element>
	<complexType name="transactionType">
		<sequence>
			<element name="OPR" type="tns:oprType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		
		<attribute name="MODULE_NAME" type="string"></attribute>
		<attribute name="PROCESS_NAME" type="string"></attribute>
	</complexType>
	<complexType name="oprType">
		<sequence>
			<element name="BLOCK" type="tns:blockType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="ID" type="string"></attribute>
		<attribute name="NAME" type="string"></attribute>
		<attribute name="BLOCK_SIZE" type="string"></attribute>
		<attribute name="QRY_TOT_SIZE" type="string"></attribute>
		<attribute name="TRN_MGMT" type="string"></attribute>
	</complexType>
	<complexType name="blockType">
		<sequence>
			<element name="QRY" maxOccurs="unbounded">	
			<complexType>
				<simpleContent>
					<extension base="string">
						<attribute name="ID" type="string"></attribute>
						<attribute name="COL_SIZE" type="string"></attribute>
					</extension>	
				</simpleContent>
			</complexType>		
			</element>
		</sequence>
		<attribute name="ID" type="string"></attribute>
		<attribute name="QRY_SIZE" type="string"></attribute>
		<attribute name="MANDATORY" type="string"></attribute>
		<attribute name="ROWS_INS" type="string"></attribute>
	</complexType>
	
</schema>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/CantIngredientSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="Hr" PROCESS_NAME="Ingrident Master" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="10">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD1_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID, NUM_ITEM_ID,GNUM_SLNO, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID,GDT_ENTRY_DATE, GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD2_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID,NUM_ITEM_ID,NUM_IT_ING_ID,GNUM_SLNO,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	 </QRY>
   </BLOCK>

</OPR>
 
<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="Y">
	 <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="3">
	 DELETE FROM PISWCA_CANTEEN_ITEM_INGD2_MST A WHERE  A.NUM_IT_ING_STORE_ID=? AND A.GNUM_SLNO=? AND A.GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>	
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="9">
	  UPDATE PISWCA_CANTEEN_ITEM_INGD1_MST SET NUM_ITEM_ID=?,GDT_EFFECTIVE_FRM=?,GDT_EFFECTIVE_TO=?,GNUM_ISVALID=?,GSTR_REMARKS=?,GDT_ENTRY_DATE=? WHERE NUM_IT_ING_STORE_ID=? AND GNUM_SLNO=? AND GNUM_HOSPITAL_CODE=?
	 </QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD2_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID,NUM_ITEM_ID,NUM_IT_ING_ID,GNUM_SLNO,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	 </QRY>
   </BLOCK>
	
</OPR>

<OPR ID="3" NAME="MODIFICATION1" BLOCK_SIZE="4" QRY_TOT_SIZE="4" TRN_MGMT="Y">
			
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	 UPDATE PISWCA_CANTEEN_ITEM_INGD1_MST T SET T.GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1),T.GDT_LSTMOD_DATE=?, T.GNUM_LSTMOD_SEATID=? WHERE  T.NUM_IT_ING_STORE_ID=? and T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	 UPDATE PISWCA_CANTEEN_ITEM_INGD2_MST T SET T.GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1),T.GDT_LSTMOD_DATE=?, T.GNUM_LSTMOD_SEATID=? WHERE  T.NUM_IT_ING_STORE_ID=? and T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="10">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD1_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID, NUM_ITEM_ID,GNUM_SLNO, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID,GDT_ENTRY_DATE, GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?)
	 </QRY>
	</BLOCK>
	<BLOCK ID="4" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD2_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID,NUM_ITEM_ID,NUM_IT_ING_ID,GNUM_SLNO,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	 </QRY>
   </BLOCK>
  
</OPR>
 
<OPR ID="4" NAME="MODIFICATION2" BLOCK_SIZE="4" QRY_TOT_SIZE="4" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD1_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID, NUM_ITEM_ID,GNUM_SLNO, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID,GDT_ENTRY_DATE, GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?)
	 </QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	 INSERT INTO PISWCA_CANTEEN_ITEM_INGD2_MST (GNUM_HOSPITAL_CODE,NUM_IT_ING_STORE_ID,NUM_ITEM_ID,NUM_IT_ING_ID,GNUM_SLNO,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	 </QRY>
   </BLOCK>
   <BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="5">
     UPDATE PISWCA_CANTEEN_ITEM_INGD1_MST SET GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? where NUM_IT_ING_STORE_ID=? and GNUM_HOSPITAL_CODE=? and GNUM_SLNO=?
    </QRY>
   </BLOCK>
    <BLOCK ID="4" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="5">
     UPDATE PISWCA_CANTEEN_ITEM_INGD2_MST SET GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? where NUM_IT_ING_STORE_ID=? and GNUM_HOSPITAL_CODE=? and GNUM_SLNO=?
    </QRY>
   </BLOCK>
	
</OPR>
 
<OPR ID="5" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	 UPDATE piswca_canteen_item_ingd1_mst SET GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=?, GNUM_ISVALID=0 WHERE NUM_IT_ING_STORE_ID=? AND GNUM_SLNO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="5">
	 UPDATE piswca_canteen_item_ingd2_mst SET GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=?, GNUM_ISVALID=0 WHERE NUM_IT_ING_STORE_ID=? AND GNUM_SLNO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
   </BLOCK>
	
</OPR>



 </tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/oldxml/Est_NoticeIssueSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="ESTATE" PROCESS_NAME="ShopVacate" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_NOTICE_ISSUE_DTL (GNUM_HOSPITAL_CODE, NUM_NOTICE_ID, STR_NOTICE_NO, DT_NOTICE_DATE,STR_CONTENT, DT_LAST_DATE, STR_TIME, GDT_ENTRY_DATE, GNUM_ISVALID,	GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
 </OPR>
 
<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
 <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
  <QRY ID="1" COL_SIZE="9">
  UPDATE  EST_NOTICE_ISSUE_DTL SET  STR_NOTICE_NO=?, DT_NOTICE_DATE=?, STR_CONTENT=?, DT_LAST_DATE=?, STR_TIME=?, GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=?  WHERE  GNUM_HOSPITAL_CODE=? AND NUM_NOTICE_ID=?				
  </QRY>
 </BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
 <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
  <QRY ID="1" COL_SIZE="4">
   UPDATE EST_NOTICE_ISSUE_DTL SET GNUM_ISVALID=0, GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=?  WHERE GNUM_HOSPITAL_CODE=? AND NUM_NOTICE_ID=?	
  </QRY>
 </BLOCK>
</OPR>
 




 </tns:Transaction>

=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/conferenceSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="COMITTEE" PROCESS_NAME="PressconfFile Transaction" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="9">
	 INSERT INTO PISPR_PRESS_CONF_TRN(GNUM_HOSPITAL_CODE,STR_SERIAL_NO,DT_DATE,STR_TIME,STR_VENUE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES(?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
   <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	 INSERT INTO PISPR_PRESS_CONF_COND_DTL(GNUM_HOSPITAL_CODE,STR_SERIAL_NO,DT_DATE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,STR_EMP_CODE,STR_EMP_NAME,STR_DESIGNATION,STR_DEPARTMENT) VALUES(?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
      <BLOCK ID="3" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO PISPR_PRESS_CONF_CONF_DTL(GNUM_HOSPITAL_CODE,STR_SERIAL_NO,DT_DATE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,STR_TOPIC_ABOUT,STR_RELA_TO_DEPT,STR_DESCRIPTION) VALUES(?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="2" NAME="INSERT" BLOCK_SIZE="5" QRY_TOT_SIZE="5" TRN_MGMT="Y">
    <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="2">
      DELETE FROM PISPR_PRESS_CONF_COND_DTL A WHERE A.STR_SERIAL_NO=? AND A.GNUM_HOSPITAL_CODE=?
    </QRY>
    </BLOCK>
    <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="2">
      DELETE FROM PISPR_PRESS_CONF_CONF_DTL A WHERE A.STR_SERIAL_NO=? AND A.GNUM_HOSPITAL_CODE=?
    </QRY>
    </BLOCK>
    <BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="7">
	 UPDATE PISPR_PRESS_CONF_TRN SET DT_DATE =?,STR_TIME=?,STR_VENUE=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE  STR_SERIAL_NO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
    </BLOCK>
    <BLOCK ID="4" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="13">
	 INSERT INTO PISPR_PRESS_CONF_COND_DTL(GNUM_HOSPITAL_CODE,STR_SERIAL_NO,DT_DATE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,STR_EMP_CODE,STR_EMP_NAME,STR_DESIGNATION,STR_DEPARTMENT) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
    </BLOCK>
      <BLOCK ID="5" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="12">
	 INSERT INTO PISPR_PRESS_CONF_CONF_DTL(GNUM_HOSPITAL_CODE,STR_SERIAL_NO,DT_DATE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,STR_TOPIC_ABOUT,STR_RELA_TO_DEPT,STR_DESCRIPTION) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="3" NAME="DELETE" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="2">
      UPDATE PISPR_PRESS_CONF_TRN A  SET A.GNUM_ISVALID=0 WHERE STR_SERIAL_NO=? AND A.GNUM_ISVALID=1 AND A.GNUM_HOSPITAL_CODE=?
    </QRY>
  </BLOCK>
    <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="2">
      UPDATE  PISPR_PRESS_CONF_COND_DTL A  SET A.GNUM_ISVALID=0 WHERE STR_SERIAL_NO=? AND A.GNUM_ISVALID=1 AND A.GNUM_HOSPITAL_CODE=?
    </QRY>
  </BLOCK>
    <BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
    <QRY ID="1" COL_SIZE="2">
      UPDATE  PISPR_PRESS_CONF_CONF_DTL A  SET A.GNUM_ISVALID=0 WHERE STR_SERIAL_NO=? AND A.GNUM_ISVALID=1 AND A.GNUM_HOSPITAL_CODE=?
    </QRY>
  </BLOCK>
</OPR>



</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/xml/agendaSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="AGENDA" PROCESS_NAME="AGENDA FILE TRANSACTIONS" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="13">
	 INSERT INTO PISCMM_AGENDA_FILE_TRN (GNUM_HOSPITAL_CODE,NUM_COMM_ID, STR_AGENDA_SEQ_NO, STR_BRIEF_DESC, STR_PRIORITY_LEVEL, DT_DATE_RECEIVED, NUM_DEPT_CODE, STR_REM_OF_DIR, STR_AGENDA_F_NAME,GDT_EFFECT_DATE, GDT_ENTRY_DATE, GNUM_ISVALID, GNUM_SEAT_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	 UPDATE PISCMM_AGENDA_FILE_TRN T SET T.NUM_COMM_ID=?, T.STR_BRIEF_DESC=?, T.STR_PRIORITY_LEVEL=?, T.DT_DATE_RECEIVED=?, T.NUM_DEPT_CODE=?,T.STR_REM_OF_DIR=?,T.STR_AGENDA_F_NAME=?,T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=?  WHERE T.STR_AGENDA_SEQ_NO=? and T.GNUM_HOSPITAL_CODE=? 
	</QRY>
   </BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="Y">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	 UPDATE PISCMM_AGENDA_FILE_TRN SET GNUM_ISVALID=0 WHERE STR_AGENDA_SEQ_NO=? AND GNUM_ISVALID=1 and GNUM_HOSPITAL_CODE=? 
	</QRY>
   </BLOCK>
</OPR>
</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/xml/PIS_PCDetailsSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="HR" PROCESS_NAME="PastCareerDetail" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">

<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="17">
INSERT INTO PIST_PCD_DTL ( STR_EMP_NO,NUM_PCD_NO,NUM_EVENT_ID,STR_EVENT_REASON,DT_EVENT_DATE,STR_ORDER_NO,DT_ORDER_DATE,STR_SIGN_AUTHORITY,STR_AUTHORITY_DESIG,STR_EMPLOYMENT_STATUS,STR_REMARKS,GDT_LSTMOD_DATE, GNUM_LSTMOD_SEATID, GDT_ENTRY_DATE, GNUM_ISVALID, GNUM_SEAT_ID, GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
</QRY>
</BLOCK>
</OPR>


<OPR ID="2" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="15">
UPDATE PIST_PCD_DTL A set A.NUM_EVENT_ID=?,A.STR_EVENT_REASON=?,A.STR_ORDER_NO=?,A.DT_ORDER_DATE=?,A.STR_SIGN_AUTHORITY=?,A.STR_AUTHORITY_DESIG=?,A.STR_EMPLOYMENT_STATUS=?,A.DT_EVENT_DATE=?,A.STR_REMARKS=?,A.GDT_LSTMOD_DATE=?, A.GNUM_LSTMOD_SEATID=?, A.GNUM_ISVALID=? where A.STR_EMP_NO =? and A.GNUM_HOSPITAL_CODE=? and  A.NUM_PCD_NO=?
</QRY>
</BLOCK>
</OPR>

<OPR ID="4" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="3">
UPDATE PIST_PCD_DTL A  SET A.GNUM_ISVALID=0 WHERE  A.STR_EMP_NO=? AND A.NUM_PCD_NO=? AND A.GNUM_HOSPITAL_CODE=?
</QRY>
</BLOCK>
</OPR>


</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/xml/TadaTransConfSettlementDAO.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:Transaction MODULE_NAME="PIS" PROCESS_NAME="ConfSettlement" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="2" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="24">
	 INSERT INTO PIST_CONF_SETTLE_TRN (STR_SANC_ORDER_NO,DT_SANC_DATE,STR_EMPLOYEE_CODE,STR_CURRENT_BASIC,STR_PAY_SCALE, NUM_TA_CLAIMED,NUM_DA_CLAIMED,NUM_REGISTRATION_FEE,NUM_AIRPORT_TAX,NUM_VISA_FEE,NUM_APPLICATION_FEE,NUM_HLTH_INS_CHARG,NUM_TAKEN_GRANT, NUM_TOT_AMT_CLAIMED,NUM_TOT_ADV_TAKEN,NUM_NET_AMT_CLAIMED,NUM_TOT_AMT_ADMISSIBLE,NUM_NET_AMT_ADMISSIBLE,STR_STATUS,GNUM_ISVALID,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_SEAT_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	
	 <QRY ID="1" COL_SIZE="22">
	 INSERT INTO PIST_CONF_SETTLE_DTL (STR_SANC_ORDER_NO,DT_SANC_DATE,STR_EMPLOYEE_CODE,STR_DEPT_STATION,DT_DEPT_DATE,STR_DEPT_TIME,STR_ARRV_STATION,DT_ARRV_DATE,STR_ARRV_TIME,NUM_OF_KM,STR_MODE_OF_JOURNEY,NUM_OF_DAYS,NUM_TOT_AMT_CLAIMED,STR_TICKET_NOS,NUM_AMT_ADMISSIBLE,STR_MILEAGE,STR_STATUS,GNUM_ISVALID,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_SEAT_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
		 
	</BLOCK>
	
</OPR>

<OPR ID="2" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="2" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="13">
	 UPDATE PIST_CONF_SETTLE_TRN T SET T.STR_VERIFY_STATUS=?,T.DT_VERIFY_DATE=?,T.STR_REM_FOR_VERIFY=?,T.STR_NAME_OF_HOD=?,T.STR_BILL_NUMBER=?,T.DT_BILL_DATE=?,T.STR_STATUS=?,T.GNUM_ISVALID=?,T.GDT_EFFECT_DATE=?,T.GDT_ENTRY_DATE=?,T.GNUM_SEAT_ID=? WHERE T.STR_SANC_ORDER_NO=? AND T.GNUM_HOSPITAL_CODE=?
	</QRY>
	
	 <QRY ID="1" COL_SIZE="3">
	  UPDATE PIST_CONF_SETTLE_DTL SET STR_STATUS=? WHERE STR_SANC_ORDER_NO=? AND GNUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
</OPR>


</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/xml/Comp_Trans_Pvt_Demand_AO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="COMPILATION" PROCESS_NAME="act_catMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  
  	<OPR ID="1" NAME="INSERT" BLOCK_SIZE="7" QRY_TOT_SIZE="10" TRN_MGMT="N">
  
	
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="24">
	INSERT INTO actcom_d_pvt_app_trn (GNUM_HOSPITAL_CODE,STR_DEMAND_NUMBER,DT_DEMAND_DATE,STR_RECEIVED_THROUGH,STR_GRANT_TYPE_CODE,NUM_DEPT_CODE,STR_SCHEME_CODE,STR_PROJECT_CODE,STR_DEMAND_CODE,STR_DEMAND_APPROVED,DT_DEMAND_APPROVED_DATE,STR_DEMAND_APPROVED_BY,STR_DEMAND_REMAKRS,STR_STATUS_CODE,STR_DEMAND_STATUS,STR_BILL_PASS_FOR_CHEQUE_PRE,DT_CHEQUE_PREP,NUM_TOTAL_AMOUNT,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,STR_DEMAND_RECEIVED,DT_DEMAND_RECEIVED_DATE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>

	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	INSERT INTO actcom_d_pvt_app_lp_dtl(GNUM_HOSPITAL_CODE,STR_DEMAND_NUMBER,DT_DEMAND_DATE,STR_TYP_LED_HED_CODE,STR_LED_HED_CODE,STR_STATUS_CODE,STR_DEMAND_STATUS,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="30">
	INSERT INTO actcom_d_pvt_a_exp_bo_dtl  (GNUM_HOSPITAL_CODE,STR_DEMAND_NUMBER,DT_DEMAND_DATE,STR_GRANT_TYPE_CODE,NUM_DEPT_CODE,STR_SCHEME_CODE,STR_PROJECT_CODE,NUM_PAYMENT_SLNO,STR_PAYMENT_CHK,STR_SALARY_HEAD,NUM_SALARY_AMOUNT,STR_MAJOR_HEAD_CODE,STR_SUB_MAJOR_HEAD_CODE,STR_MINOR_HEAD_CODE,STR_SUB_MINOR_HEAD_CODE,STR_AMOUNT_HEAD,STR_STATUS_CODE,STR_DEMAND_STATUS,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,
	STR_TO_GRANT_TYPE_CODE ,NUM_TO_DEPT_CODE ,STR_TO_SCHEME_CODE ,STR_TO_PROJECT_CODE ,STR_TO_MAJOR_HEAD_CODE,
  STR_TO_SUB_MAJOR_HEAD_CODE ,  STR_TO_MINOR_HEAD_CODE ,STR_TO_SUB_MINOR_HEAD_CODE) 
  VALUES   (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
		

	<BLOCK ID="4" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="30">
	INSERT INTO actcom_d_pvt_a_exp_bo_dtl  (GNUM_HOSPITAL_CODE,STR_DEMAND_NUMBER,DT_DEMAND_DATE,STR_GRANT_TYPE_CODE,NUM_DEPT_CODE,STR_SCHEME_CODE,STR_PROJECT_CODE,NUM_PAYMENT_SLNO,STR_PAYMENT_CHK,STR_SALARY_HEAD,NUM_SALARY_AMOUNT,STR_MAJOR_HEAD_CODE,STR_SUB_MAJOR_HEAD_CODE,STR_MINOR_HEAD_CODE,STR_SUB_MINOR_HEAD_CODE,STR_AMOUNT_HEAD,STR_STATUS_CODE,STR_DEMAND_STATUS,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,
	STR_TO_GRANT_TYPE_CODE ,NUM_TO_DEPT_CODE ,STR_TO_SCHEME_CODE ,STR_TO_PROJECT_CODE ,STR_TO_MAJOR_HEAD_CODE,
  STR_TO_SUB_MAJOR_HEAD_CODE ,  STR_TO_MINOR_HEAD_CODE ,STR_TO_SUB_MINOR_HEAD_CODE) 
  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>

	<BLOCK ID="5" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="2">
	  UPDATE  actcom_d_pvt_rcev_trn SET STR_DEMAND_STATUS=? WHERE STR_DEMAND_NUMBER=?
	</QRY>
	</BLOCK>
	
	 <BLOCK ID="6" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="2">
	  UPDATE  actcom_d_pvt_recv_lp_dtl SET STR_DEMAND_STATUS=? WHERE STR_DEMAND_NUMBER=?
	</QRY>
	</BLOCK>
	
	 <BLOCK ID="7" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="2">
	  UPDATE  actcom_d_pvt_r_exp_bo_dtl SET STR_DEMAND_STATUS=? WHERE STR_DEMAND_NUMBER=?
	</QRY>
	</BLOCK>
	
	
</OPR>
</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/quarterAllotSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="ESTATE" PROCESS_NAME="Quarter Allotment Details" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="N">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="33">
	 INSERT INTO  EST_PGI_QUATER_ALLOTMENT_DTL (GNUM_HOSPITAL_CODE,NUM_BUILDING_CODE,GNUM_SLNO_B,NUM_BLOCK_ID,
	 GNUM_SLNO_BLK,NUM_FLOOR_ID,GNUM_SLNO_F,NUM_QUARTER_ID,GNUM_SLNO_QTR,NUM_QUARTER_TYPE_ID,
	 GNUM_SLNO_QTY,NUM_CATEGORY_ID,STR_EMPLOYEE_CODE,NUM_ALLOTTE_REF_NO,DT_DATE_OF_ALLOTMENT,NUM_LICENSE_FEE,
	 NUM_IF_EXEMPTED,STR_SANCTION_ORDER_NO,DT_SANCTION_ORDER_DATE,STR_SANCTION_REMARKS,NUM_ELECTRICITY_AMOUNT,
	 NUM_WATER_AMOUNT,DT_POSSESSION_DATE,DT_MAX_POSSESSION_DATE,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,
	 GBL_NUM_SEAT_ID,OUT_OF_TURN_ALLOTMENT, OUT_OF_TURN_REASON, ALLOTMENT_ACCEPTED, DT_ALLOTMENT_ACC_CAN,
	  REASON_ACC_CAN) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
   <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="6">
	 UPDATE EST_QUATER_MST SET STR_STATUS_FLAG=?,GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=? WHERE NUM_QUARTER_ID=? AND GNUM_SLNO=?  AND  NUM_HOSPITAL_CODE=?
	</QRY>
   </BLOCK>
     <BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="9">
	 INSERT INTO ACTPAY_HRD_DTL (STR_EMPLOYEE_NUMBER, NUM_ALLOTMENT_NUMBER, NUM_LICENSE_AMOUNT, GDT_EFFECTIVE_FRM , GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE,  GNUM_HOSPITAL_CODE,STR_VALIDATE) VALUES (?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
  
</OPR>


<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="16">
	  UPDATE EST_PGI_QUATER_ALLOTMENT_DTL SET DT_DATE_OF_ALLOTMENT=?,NUM_LICENSE_FEE=?,NUM_IF_EXEMPTED=?,STR_SANCTION_ORDER_NO=?,DT_SANCTION_ORDER_DATE=?,STR_SANCTION_REMARKS=?,NUM_ELECTRICITY_AMOUNT=?,NUM_WATER_AMOUNT=?,DT_POSSESSION_DATE=?,DT_MAX_POSSESSION_DATE=?,GDT_EFFECT_DATE=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=?,OUT_OF_TURN_ALLOTMENT=?, OUT_OF_TURN_REASON=?  WHERE NUM_ALLOTTE_REF_NO=? 
	 </QRY>
	</BLOCK>
	     <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="4">
	 update  ACTPAY_HRD_DTL set NUM_LICENSE_AMOUNT=?, GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=? where NUM_ALLOTMENT_NUMBER=? 
	</QRY>
   </BLOCK>
	 
   
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 DELETE FROM EST_QTR_ALLOT_ELEC_METER_DTL A WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 DELETE FROM EST_QTR_ALLOT_WATER_METER_DTL A WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="4" NAME="DELETE WHOLE" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_PGI_QUATER_ALLOTMENT_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>

	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QTR_ALLOT_ELEC_METER_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QTR_ALLOT_WATER_METER_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="5" NAME="INSERT INVENTORY" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="12">
	 INSERT INTO EST_QTR_ITEMCROSSCHECK_DTL (NUM_ALLOTTE_REF_NO,DT_CROSSCHECKED_DATE,STR_ITEM_CATEGORY_NAME,STR_ITEM_NAME,NUM_ITEM_ID,STR_CHECK_LIST_STATUS,STR_CHECK_LIST_DESC,STR_ACCEPTANCE,DT_EFFECT_DATE,DT_ENTRY_DATE,NUM_IS_VALID,GBL_NUM_SEAT_ID) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) 
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="6" NAME="INSERT ELECTRICITY" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_QTR_ALLOT_ELEC_METER_DTL (NUM_ALLOTTE_REF_NO,STR_METER_BY,STR_METER_NUMBER,DT_DATE_OF_INSTALLATION,DT_DATE_OF_REMOVAL,STR_DESCRIPTION,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GBL_NUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
   </OPR>
<OPR ID="7" NAME="INSERT WATER" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_QTR_ALLOT_WATER_METER_DTL (NUM_ALLOTTE_REF_NO,STR_METER_BY,STR_METER_NUMBER,DT_DATE_OF_INSTALLATION,DT_DATE_OF_REMOVAL,STR_DESCRIPTION,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GBL_NUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="8" NAME="DELETE CHECKLIST" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="1">
	  DELETE FROM EST_QTR_ITEMCROSSCHECK_DTL A WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
</OPR>

<OPR ID="9" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="14">
	  UPDATE EST_PGI_QUATER_ALLOTMENT_DTL SET DT_DATE_OF_ALLOTMENT=?,NUM_LICENSE_FEE=?,NUM_IF_EXEMPTED=?,STR_SANCTION_ORDER_NO=?,DT_SANCTION_ORDER_DATE=?,STR_SANCTION_REMARKS=?,NUM_ELECTRICITY_AMOUNT=?,NUM_WATER_AMOUNT=?,DT_POSSESSION_DATE=?,DT_MAX_POSSESSION_DATE=?,GDT_EFFECT_DATE=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_ALLOTTE_REF_NO=?  
	</QRY>
   </BLOCK>
</OPR>
<OPR ID="10" NAME="DELETE WHOLE HRD" BLOCK_SIZE="4" QRY_TOT_SIZE="3" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_PGI_QUATER_ALLOTMENT_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>

	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QTR_ALLOT_ELEC_METER_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_QTR_ALLOT_WATER_METER_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="4" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE ACTPAY_HRD_DTL A SET A.GNUM_ISVALID=0 WHERE A.NUM_ALLOTTE_REF_NO=? 
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="11" NAME="UPDATE_ACCEPT_ALLOT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">  
   <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="7">
	  UPDATE  EST_PGI_QUATER_ALLOTMENT_DTL  SET STR_ACCEPT_FLAGE=? , DT_ACCEPT_DATE=?,DT_POSSESSION_DATE=?,DT_EXPECT_VACATION=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_ALLOTTE_REF_NO=? 
	</QRY>
   </BLOCK>
    <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="M" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="3">
	  UPDATE EST_REQ_APPLICATION_FORM_DTL A SET A.STR_FINAL_ACEP_REJ_NEX='N',A.GNUM_ISVALID=1 ,A.STR_AUTO_PRIORITY='', A.STR_MANUAL_PRIORITY='',GDT_LSTMOD_DATE=? , GNUM_LSTMOD_SEATID=?   WHERE A.NUM_APPLICATION_ID=? 
	</QRY>
   </BLOCK>
</OPR>

</tns:Transaction>
