=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/transactionSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/transactionSchema"
	xmlns:tns="http://www.example.org/transactionSchema">
	<annotation>
		<documentation xml:lang="en">
			Department schema Copyright 2000 Example.com. All rights
			reserved.
		</documentation>
	</annotation>
	<element name="Transaction" type="tns:transactionType"></element>
	<complexType name="transactionType">
		<sequence>
			<element name="OPR" type="tns:oprType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		
		<attribute name="MODULE_NAME" type="string"></attribute>
		<attribute name="PROCESS_NAME" type="string"></attribute>
	</complexType>
	<complexType name="oprType">
		<sequence>
			<element name="BLOCK" type="tns:blockType"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="ID" type="string"></attribute>
		<attribute name="NAME" type="string"></attribute>
		<attribute name="BLOCK_SIZE" type="string"></attribute>
		<attribute name="QRY_TOT_SIZE" type="string"></attribute>
		<attribute name="TRN_MGMT" type="string"></attribute>
	</complexType>
	<complexType name="blockType">
		<sequence>
			<element name="QRY" maxOccurs="unbounded">	
			<complexType>
				<simpleContent>
					<extension base="string">
						<attribute name="ID" type="string"></attribute>
						<attribute name="COL_SIZE" type="string"></attribute>
					</extension>	
				</simpleContent>
			</complexType>		
			</element>
		</sequence>
		<attribute name="ID" type="string"></attribute>
		<attribute name="QRY_SIZE" type="string"></attribute>
		<attribute name="MANDATORY" type="string"></attribute>
		<attribute name="ROWS_INS" type="string"></attribute>
	</complexType>
	
</schema>

=== anuragdes/HFMS-E-BIS-/BIS/BIS/OPT/xml/CanteenBillGenSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="CANTEEN" PROCESS_NAME="CanteenBillGeneration" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="19">
	INSERT INTO PISWCA_BILL_GEN_TRN(GNUM_HOSPITAL_CODE,STR_BILL_NUMBER,DT_BILL_DATE,NUM_CANT_CAT_ID,NUM_CANT_ID,STR_INCHARGE_NAME,STR_SALES_MAN,DT_SALES_DATE,STR_SHIFT,DT_DURATION_FROM,DT_DURATION_TO,NUM_TOTAL_AMT,STR_STATUS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID, GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="13">
	INSERT INTO PISWCA_BILL_GEN_DTL(GNUM_HOSPITAL_CODE,STR_BILL_NUMBER,DT_BILL_DATE,NUM_ITEM_ID,NUM_AMOUNT,STR_REMARKS,STR_STATUS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE, GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="4" QRY_TOT_SIZE="4" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	DELETE FROM PISWCA_BILL_GEN_TRN WHERE STR_BILL_NUMBER=? AND GNUM_HOSPITAL_CODE=? AND GNUM_ISVALID=1
	</QRY>
	</BLOCK>
	
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="19">
	INSERT INTO PISWCA_BILL_GEN_TRN(GNUM_HOSPITAL_CODE,STR_BILL_NUMBER,DT_BILL_DATE,NUM_CANT_CAT_ID,NUM_CANT_ID,STR_INCHARGE_NAME,STR_SALES_MAN,DT_SALES_DATE,STR_SHIFT,DT_DURATION_FROM,DT_DURATION_TO,NUM_TOTAL_AMT,STR_STATUS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID, GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	DELETE FROM PISWCA_BILL_GEN_DTL WHERE STR_BILL_NUMBER=? AND GNUM_HOSPITAL_CODE=? AND GNUM_ISVALID=1
	</QRY>
	</BLOCK>
	
	<BLOCK ID="4" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="13">
	INSERT INTO PISWCA_BILL_GEN_DTL(GNUM_HOSPITAL_CODE,STR_BILL_NUMBER,DT_BILL_DATE,NUM_ITEM_ID,NUM_AMOUNT,STR_REMARKS,STR_STATUS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE, GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="D" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	UPDATE PISWCA_BILL_GEN_TRN SET GNUM_ISVALID=0 WHERE STR_BILL_NUMBER=? AND GNUM_HOSPITAL_CODE=? 
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="D" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	UPDATE PISWCA_BILL_GEN_DTL SET GNUM_ISVALID=0 WHERE STR_BILL_NUMBER=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>

</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/hospitalBillDtlSchemaDAO.xml
<tns:Transaction MODULE_NAME="ESTATE" PROCESS_NAME="hospitalbillDetails" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="29">
	 INSERT INTO EST_HOSPITAL_BILL_DTL (NUM_HOSPITAL_ID,NUM_BILL_REFERENCE_NO,STR_BILL_NUMBER,STR_EXPENDITURE_HEAD_NAME,STR_ESI_NO,STR_EPF_NO,STR_PAN_NO,NUM_NO_OF_CALLS,NUM_VEHICLE_ID,STR_REQ_SLIP_NO,DT_FUEL_FILLING_DATE,NUM_SUPPLIER_ID,NUM_QUANTITY,NUM_TAX_AMOUNT,STR_SUPPLIER_WORK_ORDER_NO,DT_REPAIR_DATE,DT_PAYMENT_DATE,DT_BILL_FRM_DATE,DT_BILL_TO_DATE,DT_BILL_DUE_DATE,NUM_BILL_AMOUNT,STR_BRIEF_DTL,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GBL_NUM_SEAT_ID,STR_BILL_NATURE_NAME,STR_TELEPHONE_NUMBER,NUM_NO_OF_CALLS) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="23">
	 UPDATE EST_HOSPITAL_BILL_DTL SET STR_EXPENDITURE_HEAD_NAME=?,STR_ESI_NO=?,STR_EPF_NO=?,STR_PAN_NO=?,NUM_NO_OF_CALLS=?,NUM_VEHICLE_ID=?,STR_REQ_SLIP_NO=?,DT_FUEL_FILLING_DATE=?,NUM_SUPPLIER_ID=?,NUM_QUANTITY=?,NUM_TAX_AMOUNT=?,STR_SUPPLIER_WORK_ORDER_NO=?,DT_REPAIR_DATE=?,DT_PAYMENT_DATE=?,DT_BILL_FRM_DATE=?,DT_BILL_TO_DATE=?,DT_BILL_DUE_DATE=?,NUM_BILL_AMOUNT=?,STR_BRIEF_DTL=?,GDT_EFFECT_DATE=?,GDT_LSTMOD_DATE=?,GDT_LSTMOD_SEATID=? WHERE GNUM_ISVALID=1 AND NUM_BILL_REFERENCE_NO=?
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="1">
	 UPDATE EST_HOSPITAL_BILL_DTL SET GNUM_ISVALID=0 WHERE NUM_BILL_REFERENCE_NO=?
	</QRY>
	</BLOCK>
</OPR>


<OPR ID="4" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="10">
	UPDATE EST_HOSPITAL_BILL_DTL SET STR_INSTRUMENT_TYPE=?,DT_BILL_DUE_DATE=?,STR_INSTRUMENT_NUMBER=?,DT_INSTRUMENT_DATE=?,DT_INSTR_RECEV_DATE=?,STR_BANK_NAME=?,NUM_BILL_AMOUNT_TO_PAID=?,GDT_LSTMOD_DATE=?,GDT_LSTMOD_SEATID=? WHERE GNUM_ISVALID=1 AND NUM_BILL_REFERENCE_NO=?
	</QRY>
	</BLOCK>
</OPR>
</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/oldxml/DietCostPrepSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="CANTEEN" PROCESS_NAME="CanteenDietCostPreparation" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="Y">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="19">
	INSERT INTO PISWCA_CAN_DIET_PREP_TRN ( GNUM_HOSPITAL_CODE,DT_FOR_PREPARATION ,NUM_CANT_ID, NUM_DIET_NO ,STR_SHIFT,NUM_ITEM_ID, NUM_ITEM_QTY,NUM_UNIT_ID,NUM_TOTAL_COST,NUM_COST_PER_UNIT,NUM_COST_FOR_SALE, STR_STATUS, GDT_LSTMOD_DATE, GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,NUM_FINAL_TOTAL_COST) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="15">
	INSERT INTO PISWCA_CAN_DIET_PREP_DTL (GNUM_HOSPITAL_CODE,DT_FOR_PREPARATION,NUM_CANT_ID,NUM_DIET_NO,NUM_ITEM_ID,NUM_INGREDIENT_ITEM_ID,NUM_QTY,NUM_COST,STR_STATUS,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID,GDT_EFFECT_DATE, GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
<QRY ID="1" COL_SIZE="5">
UPDATE PISWCA_CAN_DIET_PREP_TRN SET NUM_COST_FOR_SALE=? ,GDT_LSTMOD_DATE=?, GNUM_LSTMOD_SEATID=? WHERE NUM_DIET_NO=? AND GNUM_HOSPITAL_CODE=? AND GNUM_ISVALID=1
</QRY>
</BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="D" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	UPDATE PISWCA_CAN_DIET_PREP_TRN SET GNUM_ISVALID=0 WHERE NUM_DIET_NO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="D" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	UPDATE PISWCA_CAN_DIET_PREP_DTL SET GNUM_ISVALID=0 WHERE NUM_DIET_NO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>



<OPR ID="4" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="D" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	DELETE FROM PISWCA_CAN_DIET_PREP_TRN WHERE NUM_DIET_NO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="D" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="2">
	DELETE FROM PISWCA_CAN_DIET_PREP_DTL WHERE NUM_DIET_NO=? AND GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>





</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT/oldxml/ActPayLicSubs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="PAYROLL" PROCESS_NAME="Lic Subscription" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="16">
	 INSERT INTO ACTPAY_LIC_SUBS_TRNS(str_employee_number,dt_date_of_subscription,num_lic_premium,str_lic_policy_no,str_policy_no, dt_maturity_date, num_policy_amount, num_payment_type, gnum_slno, gnum_isvalid, gnum_seat_id, gdt_entry_date, gdt_lstmod_date, gnum_lstmod_seatid, gstr_remarks,gnum_hospital_code) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	 INSERT INTO ACTPAY_LIC_SUBS_TRNS_LOG(str_employee_number,dt_date_of_subscription,num_lic_premium,str_lic_policy_no,str_policy_no, dt_maturity_date, num_policy_amount, num_payment_type,NUM_NUMBER_OF_PREMIUM,NUM_NUMBER_OF_PREMIUM_PAID,NUM_ACTIVE_STATUS, gnum_slno, gnum_isvalid, gnum_seat_id, gdt_entry_date, gdt_lstmod_date, gnum_lstmod_seatid, gstr_remarks,gnum_hospital_code) SELECT str_employee_number,dt_date_of_subscription,num_lic_premium,str_lic_policy_no,str_policy_no, dt_maturity_date, num_policy_amount, num_payment_type,NUM_NUMBER_OF_PREMIUM,NUM_NUMBER_OF_PREMIUM_PAID,NUM_ACTIVE_STATUS, ?, gnum_isvalid, gnum_seat_id, gdt_entry_date, ?, ?, gstr_remarks,gnum_hospital_code FROM  ACTPAY_LIC_SUBS_TRNS M WHERE  M.str_employee_number =? AND M.STR_LIC_POLICY_NO=? AND M.GNUM_HOSPITAL_CODE=?  
	 </QRY>
	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="15">
	 UPDATE actpay_lic_subs_trns SET DT_DATE_OF_SUBSCRIPTION=TO_DATE(?,'DD-MON-YYYY'), NUM_LIC_PREMIUM=?,STR_LIC_POLICY_NO=?,STR_POLICY_NO=?, DT_MATURITY_DATE=TO_DATE(?,'DD-MON-YYYY'),NUM_POLICY_AMOUNT=?,NUM_PAYMENT_TYPE=?,GNUM_SLNO=?,GNUM_ISVALID=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=?,GNUM_HOSPITAL_CODE=? WHERE  str_employee_number =? AND STR_LIC_POLICY_NO=? AND GNUM_HOSPITAL_CODE=? 
	 </QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="DELETE" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	  INSERT INTO ACTPAY_LIC_SUBS_TRNS_LOG(str_employee_number,dt_date_of_subscription,num_lic_premium,str_lic_policy_no,str_policy_no, dt_maturity_date, num_policy_amount, num_payment_type,NUM_NUMBER_OF_PREMIUM,NUM_NUMBER_OF_PREMIUM_PAID,NUM_ACTIVE_STATUS, gnum_slno, gnum_isvalid, gnum_seat_id, gdt_entry_date, gdt_lstmod_date, gnum_lstmod_seatid, gstr_remarks,gnum_hospital_code) SELECT str_employee_number,dt_date_of_subscription,num_lic_premium,str_lic_policy_no,str_policy_no, dt_maturity_date, num_policy_amount, num_payment_type,NUM_NUMBER_OF_PREMIUM,NUM_NUMBER_OF_PREMIUM_PAID,NUM_ACTIVE_STATUS, ?, '0', gnum_seat_id, gdt_entry_date, ?, ?, gstr_remarks,gnum_hospital_code FROM  ACTPAY_LIC_SUBS_TRNS M WHERE  M.str_employee_number =? AND M.STR_LIC_POLICY_NO=? AND M.GNUM_HOSPITAL_CODE=?  
    	 </QRY>
   	</BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="3">
	  delete actpay_lic_subs_trns T   WHERE  T.STR_EMPLOYEE_NUMBER=? AND T.STR_LIC_POLICY_NO=? AND T.GNUM_HOSPITAL_CODE=?
     </QRY>
   </BLOCK>
</OPR>



</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/ftsdenominationSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="FTS" PROCESS_NAME="DenominationMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="11">
	 INSERT INTO FTS_DENOMINATION_MST(NUM_DENOMINATION_ID,STR_DENOMINATION_TYPE,NUM_ALERT_AMOUNT_LESS,GNUM_SLNO,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GSTR_REMARKS,GDT_ENTRY_DATE,GNUM_ISVALID,GNUM_SEAT_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="11">
	 UPDATE FTS_DENOMINATION_MST SET STR_DENOMINATION_TYPE=?,NUM_ALERT_AMOUNT_LESS=?,GDT_EFFECTIVE_FRM=?,GDT_EFFECTIVE_TO=?,GSTR_REMARKS=?,GNUM_ISVALID=?,GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=? WHERE NUM_DENOMINATION_ID=? AND GNUM_SLNO=? and GNUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="3" NAME="MODIFY" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	 UPDATE FTS_DENOMINATION_MST T SET T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=?,T.GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1) WHERE  T.NUM_DENOMINATION_ID=?  and T.GNUM_SLNO=? AND gnum_hospital_code=?
	 </QRY>
	 </BLOCK>
		
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="11">
	 INSERT INTO FTS_DENOMINATION_MST(gnum_hospital_code,NUM_DENOMINATION_ID,GNUM_SLNO,STR_DENOMINATION_TYPE,NUM_ALERT_AMOUNT_LESS,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>		
</OPR>
<OPR ID="4" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	 UPDATE FTS_DENOMINATION_MST SET GDT_LSTMOD_DATE=?,GNUM_LSTMOD_SEATID=?,GNUM_ISVALID=0 WHERE NUM_DENOMINATION_ID=? AND GNUM_SLNO=? AND gnum_hospital_code=?
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="6" NAME="MODIFICATION" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="11">
	INSERT INTO FTS_DENOMINATION_MST(gnum_hospital_code,NUM_DENOMINATION_ID,GNUM_SLNO,STR_DENOMINATION_TYPE,NUM_ALERT_AMOUNT_LESS,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID,GNUM_SEAT_ID,GDT_ENTRY_DATE,GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
   <BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	 UPDATE FTS_DENOMINATION_MST T SET T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=? WHERE T.NUM_DENOMINATION_ID=? AND T.GNUM_SLNO=? AND T.gnum_hospital_code=?
	 </QRY>
	</BLOCK>
</OPR>
<OPR ID="7" NAME="MODIFICATION" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
  <BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	INSERT INTO FTS_DENOMINATION_MST(NUM_DENOMINATION_ID,GNUM_SLNO,STR_DENOMINATION_TYPE,NUM_ALERT_AMOUNT_LESS,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GSTR_REMARKS,GNUM_ISVALID,GDT_LSTMOD_DATE,GNUM_LSTMOD_SEATID) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
   </BLOCK>
</OPR>
</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/DED_PRI.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="PAYROLL" PROCESS_NAME="DPMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
<OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="14">
	 INSERT INTO ACTPAY_DED_PRI_MST (STR_DEDUCTION_CODE,STR_DEDUCTION_TYPE,NUM_DED_PRIORITY,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE, GDT_LSTMOD_DATE, GNUM_LSTMOD_SEATID, GSTR_REMARKS,GNUM_SLNO,NUM_DEDUCTION_PRI_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="13">
	 UPDATE  ACTPAY_DED_PRI_MST  SET STR_DEDUCTION_CODE=?,STR_DEDUCTION_TYPE=?,NUM_DED_PRIORITY=?,GDT_EFFECTIVE_FRM=TO_DATE(?,'DD-MON-YYYY'),GDT_EFFECTIVE_TO=TO_DATE(?,'DD-MON-YYYY'),GNUM_ISVALID=?,GNUM_SEAT_ID=?,GDT_ENTRY_DATE=?,GSTR_REMARKS=? ,GNUM_HOSPITAL_CODE=? WHERE  GNUM_SLNO=? AND NUM_DEDUCTION_PRI_ID=? AND GNUM_HOSPITAL_CODE=?
	 </QRY>
	</BLOCK>
</OPR>

<OPR ID="4" NAME="MODIFICATION" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="6">
	   UPDATE ACTPAY_DED_PRI_MST T SET GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1),GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')),GNUM_LSTMOD_SEATID=? WHERE T.NUM_DEDUCTION_PRI_ID=? AND T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="12">
	 INSERT INTO ACTPAY_DED_PRI_MST  (STR_DEDUCTION_CODE,STR_DEDUCTION_TYPE,NUM_DED_PRIORITY,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID, GDT_ENTRY_DATE, GNUM_SEAT_ID, GSTR_REMARKS, GNUM_SLNO, NUM_DEDUCTION_PRI_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="5" NAME="MODIFICATION" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	   UPDATE ACTPAY_DED_PRI_MST T SET GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')),GNUM_LSTMOD_SEATID=? WHERE T.NUM_DEDUCTION_PRI_ID=? AND T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="12">
	 INSERT INTO ACTPAY_DED_PRI_MST  (STR_DEDUCTION_CODE,STR_DEDUCTION_TYPE,NUM_DED_PRIORITY,GDT_EFFECTIVE_FRM,GDT_EFFECTIVE_TO,GNUM_ISVALID, GDT_ENTRY_DATE, GNUM_SEAT_ID, GSTR_REMARKS, GNUM_SLNO, NUM_DEDUCTION_PRI_ID,GNUM_HOSPITAL_CODE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>
<OPR ID="6" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	  UPDATE ACTPAY_DED_PRI_MST T  SET T.GNUM_ISVALID=0,GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')),GNUM_LSTMOD_SEATID=? WHERE  T.NUM_DEDUCTION_PRI_ID=? AND T.GNUM_SLNO=? AND T.GNUM_HOSPITAL_CODE=?
     </QRY>
   </BLOCK>
</OPR>

</tns:Transaction>

=== anuragdes/HFMS-E-BIS-/OPT_OLD/xml/compcatSchemaDAO.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Transaction MODULE_NAME="ESTATE" PROCESS_NAME="complaintcategoryMaster" xmlns:tns="http://www.example.org/transactionSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/transactionSchema transactionSchema.xsd ">
  <OPR ID="1" NAME="INSERT" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_COMPLAINT_CAT_MST (NUM_HOSPITAL_CODE, NUM_COMPLAIN_CATEGORY_ID, GNUM_SLNO, STR_COMPLAIN_CATEGORY_NAME, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE,  GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="2" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="8">
	 UPDATE EST_COMPLAINT_CAT_MST SET STR_COMPLAIN_CATEGORY_NAME=?,GNUM_ISVALID=?, GDT_EFFECTIVE_FRM=TO_DATE(?,'DD-MON-YYYY'),GDT_EFFECTIVE_TO=TO_DATE(?,'DD-MON-YYYY'),GSTR_REMARKS=? WHERE NUM_COMPLAIN_CATEGORY_ID=? AND GNUM_SLNO=? AND NUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="3" NAME="MODIFICATION" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="3">
	  UPDATE EST_COMPLAINT_CAT_MST T SET T.GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1) WHERE T.NUM_COMPLAIN_CATEGORY_ID=? AND T.GNUM_SLNO=?
	 </QRY>
	 </BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="12">
	 INSERT INTO EST_COMPLAINT_CAT_MST (NUM_HOSPITAL_CODE, NUM_COMPLAIN_CATEGORY_ID, GNUM_SLNO, STR_COMPLAIN_CATEGORY_NAME, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE, GDT_LSTMOD_DATE, GNUM_LSTMOD_SEATID,  GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="4" NAME="DELETE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="5">
	  UPDATE EST_COMPLAINT_CAT_MST T  SET T.GDT_LSTMOD_DATE=?,T.GNUM_LSTMOD_SEATID=?,  T.GNUM_ISVALID=0 WHERE  T.NUM_COMPLAIN_CATEGORY_ID=? AND T.GNUM_SLNO=? AND T.NUM_HOSPITAL_CODE=?
     </QRY>
   </BLOCK>
</OPR>

<OPR ID="5" NAME="UPDATE" BLOCK_SIZE="1" QRY_TOT_SIZE="1" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="7">
	 UPDATE EST_COMPLAINT_CAT_MST SET STR_COMPLAIN_CATEGORY_NAME=?,GNUM_ISVALID=?, GDT_EFFECTIVE_FRM=?,GSTR_REMARKS=? WHERE NUM_COMPLAIN_CATEGORY_ID=? AND GNUM_SLNO=? AND NUM_HOSPITAL_CODE=?
	</QRY>
	</BLOCK>
</OPR>

<OPR ID="6" NAME="MODIFY" BLOCK_SIZE="3" QRY_TOT_SIZE="3" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="4">
	  UPDATE EST_COMPLAINT_CAT_MST T SET T.GDT_EFFECTIVE_TO=(TO_DATE(?,'DD-MON-YYYY')-1) WHERE T.NUM_COMPLAIN_CATEGORY_ID=? AND T.GNUM_SLNO=? AND T.NUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	 <QRY ID="1" COL_SIZE="10">
	  INSERT INTO EST_COMPLAINT_CAT_MST (NUM_HOSPITAL_CODE, NUM_COMPLAIN_CATEGORY_ID, GNUM_SLNO, STR_COMPLAIN_CATEGORY_NAME, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE,  GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
	<BLOCK ID="3" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="5">
	  UPDATE EST_COMPLAINT_CAT_MST T SET  T.GDT_LSTMOD_DATE=(TO_DATE(?,'DD-MON-YYYY')), T.GNUM_LSTMOD_SEATID=? WHERE T.NUM_COMPLAIN_CATEGORY_ID=? AND T.GNUM_SLNO=? AND T.NUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
</OPR>

<OPR ID="7" NAME="MODIFYNEXT" BLOCK_SIZE="2" QRY_TOT_SIZE="2" TRN_MGMT="N">
	<BLOCK ID="1" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="5">
	  UPDATE EST_COMPLAINT_CAT_MST T SET  T.GDT_LSTMOD_DATE=?, T.GNUM_LSTMOD_SEATID=? WHERE T.NUM_COMPLAIN_CATEGORY_ID=? AND T.GNUM_SLNO=? AND T.NUM_HOSPITAL_CODE=?
	 </QRY>
	 </BLOCK>
	<BLOCK ID="2" QRY_SIZE="1" ROWS_INS="S" MANDATORY="Y">
	<QRY ID="1" COL_SIZE="10">
	 INSERT INTO EST_COMPLAINT_CAT_MST (NUM_HOSPITAL_CODE, NUM_COMPLAIN_CATEGORY_ID, GNUM_SLNO, STR_COMPLAIN_CATEGORY_NAME, GDT_EFFECTIVE_FRM, GDT_EFFECTIVE_TO, GNUM_ISVALID, GNUM_SEAT_ID, GDT_ENTRY_DATE,  GSTR_REMARKS) VALUES (?,?,?,?,?,?,?,?,?,?)
	</QRY>
	</BLOCK>
</OPR>

</tns:Transaction>
